name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install development dependencies
      run: |
        pip install flake8 bandit safety mypy coverage pytest pytest-bdd

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Run BDD tests
      run: |
        pytest features/ --force-bdd

    - name: Generate test report
      run: |
        pytest --html=reports/test_report.html --self-contained-html

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: reports/test_report.html

    - name: Run code quality checks
      run: |
        flake8 .

    - name: Run security checks
      run: |
        bandit -r src

    - name: Check for vulnerable dependencies
      run: |
        safety check

    - name: Run type checks
      run: |
        mypy src

    - name: Run custom tests
      run: |
        python run_tests.py